{% set name = "testgres" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/postgrespro/testgres/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6881af9697cbac82d8a560777c20f9cdfeb8840410fcff8ec5cc6880770d88bf


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pg8000
    - port-for >=0.4
    - six >=1.9.0
    - psutil
    - packaging

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - testgres
    - testgres.operations

about:
  home: https://github.com/postgrespro/testgres
  license: PostgreSQL
  license_family: MIT
  license_file: LICENSE
  summary: 'Testing utility for PostgreSQL and its extensions.'

extra:
  recipe-maintainers:
    - demonolock
